2024-03-24 17:01:06 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[webkit] (setup)[0m
curl - X GET 'http://localhost:8111/authenticationTest.html?csrf' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:*/*'
-H 'Connection:keep-alive'
-H 'Authorization:Basic OjM3NjM3NDk3ODAwOTg3ODM1NzE=' 
-d ''
2024-03-24 17:01:47 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[webkit] (teardown)[0m
curl - X DELETE 'http://localhost:8111/app/rest/projects/id:hkAKk8sq2vr' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:application/json'
-H 'Connection:keep-alive'
-H 'Content-Type:application/json'
-H 'X-TC-CSRF-Token:9fa48242-1f9f-40db-9818-7bf2c6c573f8'
-H 'Cookie:TCSESSIONID=5E267AFDE40BCE115596DF38CEDD8C97'
-H 'Content-Length:0'
-H 'Authorization:Basic OjM3NjM3NDk3ODAwOTg3ODM1NzE=' 
-d '' 
 

2024-03-24 17:01:47 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by locator 'count:1,id:hkAKk8sq2vr'. Project cannot be found by external id 'hkAKk8sq2vr'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m