2024-03-26 19:29:40 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[chromium] (setup)[0m
curl - X GET 'http://localhost:8111/authenticationTest.html?csrf' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:*/*'
-H 'Connection:keep-alive'
-H 'Authorization:Basic OjM4MTA3MzU1MDY1ODE4MzAwNDE=' 
-d ''
2024-03-26 19:29:56 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[chromium] (teardown)[0m
curl - X GET 'http://localhost:8111/authenticationTest.html?csrf' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:application/json'
-H 'Connection:keep-alive'
-H 'Content-Type:application/json'
-H 'X-TC-CSRF-Token:ba61127d-b8b5-40c4-9c87-4c5f62eac2ba'
-H 'Cookie:TCSESSIONID=76D9822B0B1D2E17CDC2CFB7E597591A'
-H 'Authorization:Basic OjM4MTA3MzU1MDY1ODE4MzAwNDE=' 
-d '' 
 

2024-03-26 19:29:56 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[chromium] (teardown)[0m
curl - X DELETE 'http://localhost:8111/app/rest/projects/id:PsnAzIaLIbL' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:application/json'
-H 'Connection:keep-alive'
-H 'Content-Type:application/json'
-H 'X-TC-CSRF-Token:ba61127d-b8b5-40c4-9c87-4c5f62eac2ba'
-H 'Cookie:TCSESSIONID=76D9822B0B1D2E17CDC2CFB7E597591A'
-H 'Content-Length:0'
-H 'Authorization:Basic OjM4MTA3MzU1MDY1ODE4MzAwNDE=' 
-d '' 
 

2024-03-26 19:29:56 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by locator 'count:1,id:PsnAzIaLIbL'. Project cannot be found by external id 'PsnAzIaLIbL'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m